
# This is a Dropwizard-based configuration file, see the documentation at
# http://www.dropwizard.io for additional configuration information.

# Cassandra connection information
cassandraKeyspace: newts
cassandraHost: localhost
cassandraPort: 9042

logging:
  level: DEBUG

reports:
  gsod:
    interval: 3600
    datasources:
      - label: meanTemp
        source: meanTemperature
        function: AVERAGE
        heartbeat: 7200
      - label: maxTemp
        source: maxTemperature
        function: AVERAGE
        heartbeat: 7200
      - label: minTemp
        source: minTemperature
        function: AVERAGE
        heartbeat: 7200
    exports:
      - meanTemp

  temps:
    interval: 300
    datasources:
      - label: inlet
        source: inlet
        function: AVERAGE
        heartbeat: 600
    exports:
      - inlet

  octets:
    interval: 300
    datasources:
      - label: inOctets
        source: ifInOctets
        heartbeat: 600
        function: AVERAGE
      - label: outOctets
        source: ifOutOctets
        heartbeat: 600
        function: AVERAGE
    exports:
      - inOctets
      - outOctets