
# This is a Dropwizard-based configuration file, see the documentation at
# http://www.dropwizard.io for additional configuration information.

# Cassandra connection information
cassandraKeyspace: newts
cassandraHost: localhost
cassandraPort: 9042

reports:
  gsod:
    interval: 3600000
    datasources:
      - label: temperature
        source: meanTemperature
        function: AVERAGE
        heartbeat: 600000
    exports:
      - temperature

  temps:
    interval: 300000
    datasources:
      - label: inlet
        source: inlet
        function: AVERAGE
        heartbeat: 600000
    exports:
      - inlet

  octets:
    interval: 300000
    datasources:
      - label: inOctets
        source: ifInOctets
        heartbeat: 600000
        function: AVERAGE
      - label: outOctets
        source: ifOutOctets
        heartbeat: 600000
        function: AVERAGE
    exports:
      - inOctets
      - outOctets